### ISSUE TITLE
Machine Executor Needs to be Updated by 5/31/22 per Circle CI

### ISSUE THREAD

**Issue by pdumontel** [jfrog/artifactory-orb#13]
### Orb version
1.0.1

### What happened

Per https://circleci.com/docs/2.0/images/linux-vm/14.04-to-20.04-migration/, an executor with machine: true needs to be migrated to machine: image: ubuntu-2004:current (or some other version) by 5/31/22.
We use the orb in our projects and received emails from Circle CI that our builds were affected by this change.

### Expected behavior
update the executor to use the new image.

**Comment by pdumontel** [comment]
I think this change to machine.yml should work:

```
description: >
  A machine executor that can run Docker commands:
  https://circleci.com/docs/2.0/executor-types/#using-machine

machine:
  image: ubuntu-2004:current
```

**Comment by toozej-work** [comment]
@eyalbe4 @yahavi @Ohad2Levy can you also publish a new version of this orb such that it shows up on https://circleci.com/developer/orbs/orb/jfrog/artifactory-orb as a new version. Without a new version of this orb published no one will be able to use these changes. Thanks!

**Comment by pdumontel** [comment]
This is still not published to Circle CI; https://circleci.com/developer/orbs/orb/jfrog/artifactory-orb still shows latest version is from 2019.
